apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
spec:
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        service: udagram-reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: kalffman/udagram-reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


---

apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
spec:
  type: NodePort
  selector:
    service: udagram-reverseproxy
  ports:
  - port: 8080
    targetPort: 8080