apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
spec:
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: kalffman/udagram-frontend
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-service
spec:
  type: NodePort
  selector:
    app: udagram-frontend
  ports:
  - port: 8080

