apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
spec:
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: kalffman/udagram-api-user
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: POSTGRES_USERNAME
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_HOST
            value: "udagram-db.cut0mushv90q.sa-east-1.rds.amazonaws.com"
          - name: POSTGRES_DB
            value: "postgres"
          - name: AWS_BUCKET
            value: "udagram-884750334203-dev"
          - name: AWS_REGION
            value: "sa-east-1"
          - name: JWT_SECRET
            value: "jeff"
          - name: URL
            value: "http://localhost:8100"

---

apiVersion: v1
kind: Service
metadata:
  name: udagram-api-user-service
spec:
  selector:
    app: udagram-api-user
  ports:
  - port: 8080
    targetPort: 8080
